apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: lms-backend
        image: 083333213257.dkr.ecr.us-east-1.amazonaws.com/lms:backend
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-configmap
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_PASSWORD
      imagePullSecrets:
      - name: ecr-secret

