apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_PASSWORD: cmFnaGF2YXJhbw==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnJhZ2hhdmFyYW9AcG9zdGdyZXMuY2JtczZjZTJnejJmLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVz 
